server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone:
        http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: #路由可以选多个
        - id: service-autodeliver #我们自定义的路由id，保持唯一
          uri: http://127.0.0.1:8090  #目标服务器
          #断言：路由条件，predicate接受一个入参，返回一个布尔值结果，该接口包含多种
          #多种默认方法来将predicate组合成其他复杂的逻辑（比如：与，或，非）。
          predicates:
            - Path= /autodeliver/**
        - id: service-resume-router           #自定义的路由id，保持唯一
          uri: http://127.0.0.1:8080            #目标服务地址
          predicates:
            - path= /resume/**

