server:
  port: 8761
spring:
  application:
    name: eureka-server  #应用名称会在Eureka中作为服务名称

#eureka客户端的配置（和Server交互)
eureka:
  instance:  #当前Eureka的主机名
    hostname: nodea
  client:
    service-url:   #配置客户端所交互的Eureka server的地址
#      此时集群模式下，defaultZone应该指向其他Eureka server
      defaultZone: http://127.0.0.1:8762/eureka/
    registerWithEureka: true #是否从其他eureka获取配置
    fetchRegistry: true  #是否注册到eureka，自己就是server不需要注册自己

