server:
  port: 9999

spring:
  application:
    name: oauth2-server
eureka:
  client:
    service-url:
      defaultZone:
       http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
  instance:
    prefer-ip-address: true
    